CREATE DEFINER=`root`@`localhost` PROCEDURE `declaraciones`()
BEGIN
DECLARE v VARCHAR(20) DEFAULT "caracteres variables";
DECLARE i INTEGER DEFAULT 548;
DECLARE d DECIMAL (6,3) DEFAULT 876.265;
DECLARE f DATE DEFAULT '2021-01-01';
DECLARE ts TIMESTAMP DEFAULT current_timestamp();
SELECT v;
SELECT i;
SELECT d;
SELECT f;
SELECT ts;
END